- examples/root_spv_receive.rs
- src/lib.rs
- src/macros.rs
- src/receive.rs
This enables to select multiple message types and work with them in need. Resolves #1.
> Introduce receive utilities for message

- .travis.yml
- src/lib.rs
This PR enables this project to build on stable channel of rust. 
The issue is briefly discussed in #17
> Remove nightly features

- Cargo.toml
- src/bastion.rs
- src/context.rs
- src/runtime_system.rs
- src/supervisor.rs
> Move parking_lot to std

- bastion/src/lib.rs
This will give a clear guide of what Bastion does and how it does.
> Better documentation

- bastion-executor/src/lib.rs
- lightproc/src/layout_helpers.rs
- lightproc/src/lib.rs
- lightproc/src/state.rs
> Fix clippy errors

- bastion-executor/README.md
- bastion-executor/src/allocator.rs
- bastion-executor/src/blocking_pool.rs
- bastion-executor/src/distributor.rs
- bastion-executor/src/lib.rs
- bastion-executor/src/load_balancer.rs
- bastion-executor/src/macros.rs
- bastion-executor/src/placement.rs
- bastion-executor/src/pool.rs
- bastion-executor/src/run.rs
- bastion-executor/src/run_queue.rs
- bastion-executor/src/sleepers.rs
- bastion-executor/src/thread_recovery.rs
- bastion-executor/src/worker.rs
- bastion/examples/getting_started.rs
- bastion/src/lib.rs
- bastion/src/system.rs
- lightproc/README.md
Partially implements #59 and #61
> Bastion Executor Documentation

- bastion/src/bastion.rs
- bastion/src/children.rs
- bastion/src/context.rs
- bastion/src/lib.rs
- bastion/src/message.rs
- bastion/src/supervisor.rs
- bastion/src/system.rs
> Added logs

- bastion/src/bastion.rs
- bastion/src/broadcast.rs
- bastion/src/lib.rs
- bastion/src/system.rs
Hey :wave:!
I removed all the `unsafe` code from the `bastion` crate and added `#![deny(unsafe_code)]` to it :).
Related: #104
> Removed all unsafe code from "bastion"

- bastion/src/children.rs
- bastion/tests/prop_children_broadcast.rs
- bastion/tests/prop_children_redundancy.rs
Fixes lower bound for the redundancy and related children proptest
> Redundancy boundaries

- bastion/src/message.rs
> Updated msg! to allow explicit and implicit returns

- bastion-executor/src/distributor.rs
- bastion-executor/src/placement.rs
- lightproc/src/lightproc.rs
Stat sampler improvements and minor fixes
> Stat sampler improvements

- bastion/examples/middleware.rs
- bastion/tests/prop_children_broadcast.rs
- bastion/tests/prop_children_message.rs
- bastion/tests/prop_children_redundancy.rs
Fixed warnings in tests and examples.
This PR is supposed to be merged after #130
> Fix warnings

- Cargo.toml
- bastion-executor/Cargo.toml
- bastion-executor/src/blocking.rs
- bastion-executor/src/lib.rs
- bastion-utils/Cargo.toml
- bastion-utils/README.md
- bastion-utils/src/lib.rs
- bastion-utils/src/math.rs
Adds a utilities crate as a starting point for shared code.
> Bastion Utilities Crate

- bastion-utils/Cargo.toml
> bastion-utils: Add missing readme reference to cargo.toml

- .github/workflows/ci.yml
- bastion-executor/examples/run.rs
- bastion-executor/examples/spawn_async.rs
- bastion/src/child.rs
- bastion/src/children.rs
- bastion/src/system.rs
- bastion/tests/message_signatures.rs
- lightproc/examples/proc_panic.rs
- lightproc/examples/proc_run.rs
- lightproc/examples/state_change.rs
- lightproc/src/lib.rs
- lightproc/src/lightproc.rs
- lightproc/src/proc_handle.rs
- lightproc/src/proc_stack.rs
- lightproc/src/proc_state.rs
- lightproc/src/raw_proc.rs
- lightproc/src/recoverable_handle.rs
- lightproc/tests/stack.rs
> Stateful ProcStack

- .github/workflows/ci.yml
- .github/workflows/clippy.yml
actions/checkout v2 improves performance and we use `actions/checkout@master` in other place so this should be reasonable.
> Use `actions/checkout@master` in Clippy check

- .auto-changelog
- bastion/examples/restart_strategy.rs
> Changelog config

- lightproc/src/recoverable_handle.rs
> Remove debug statements in lightproc code

- bastion/src/child_ref.rs
- bastion/src/children_ref.rs
> Make ChildRef::path and ChildrenRef::path public

- SECURITY.md
Set up a minimal security policy. If you want to add more content, just let me know or add directly.
Fixes #175
r? @vertexclique
> Set up security policy

- bastion/src/supervisor.rs
This pull request contains changes for documentation, rendered in docs.rs
> Fixed documentation for RestartStrategy struct

- bastion/src/children.rs
> Removed excessive register call for dispatchers

- bastion-executor/Cargo.toml
- bastion-executor/benches/stats.rs
- bastion-executor/src/load_balancer.rs
- bastion-executor/src/worker.rs
> replace lockbased stats with lockless based stats.

- bastion-executor/src/load_balancer.rs
Signed-off-by: Tiger <rbalajis25@gmail.com>
> Bump MAX_CORE to support more core

- bastion/src/child.rs
- bastion/src/children.rs
- bastion/src/supervisor.rs
- bastion/src/system.rs
> Moving state machine handlers into separate functions 

- .github/workflows/miri.yml
- bastion-executor/src/sleepers.rs
- bastion/src/dispatcher.rs
> Add miri over here

- bastion/examples/broadcast_message.rs
- bastion/src/children.rs
- bastion/src/dispatcher.rs
Fix #185 
do we wanna add documentation to it ? no idea what to say tbh ^^'
> Use round-robin as the default dispatcher handler.

- src/bastion/examples/broadcast_message.rs
- src/bastion/examples/fibonacci.rs
> Fibonacci starter example

- src/bastion-executor/src/placement.rs
- src/bastion/Cargo.toml
- src/bastion/examples/broadcast_message.rs
- src/bastion/examples/fibonacci.rs
- src/bastion/examples/prime_numbers.rs
- src/bastion/src/bastion.rs
- src/bastion/src/child.rs
- src/bastion/src/child_ref.rs
- src/bastion/src/children.rs
- src/bastion/src/children_ref.rs
- src/bastion/src/context.rs
- src/bastion/src/dispatcher.rs
- src/bastion/src/lib.rs
- src/bastion/src/message.rs
- src/bastion/src/supervisor.rs
- src/bastion/src/system.rs
add example in boardcast_message so the user can change the log level
fix some warning
Close #102
> feat: use `tracing` as the log crate, and remove `log` crate

- .github/workflows/miri.yml
- src/bastion/Cargo.toml
- src/bastion/src/dispatcher.rs
Brought concurrent table + transactional memory to Bastion internals. Will bring transactional memory to actors too. Rite of passage for Bastion!
> Lever – Hello transactional memory

- README.md
It's actually a bit hard to figure out what is bastion and is ecosystem.
In this PR we will collect the information of the different elements which composed the bastion ecosystem. And add a quick introduction to explain it.
The initiative is described in the #192 issue.
> Add overview from bastion ecosystem

- src/bastion/Cargo.toml
- src/bastion/src/bastion.rs
- src/bastion/src/child.rs
- src/bastion/src/children.rs
> Make with_exec non-sync

- src/bastion/src/children_ref.rs
Signed-off-by: Tiger <rbalajis25@gmail.com>
Fix #137
> Route all the failed message to dead letter children.

- .github/workflows/miri.yml
- src/bastion-executor/examples/spawn_async.rs
- src/bastion-executor/src/load_balancer.rs
- src/bastion-executor/src/placement.rs
- src/bastion-executor/src/run_queue.rs
- src/bastion-executor/src/sleepers.rs
- src/bastion/Cargo.toml
- src/bastion/examples/broadcast_message.rs
- src/bastion/examples/fibonacci.rs
- src/bastion/examples/prime_numbers.rs
- src/bastion/examples/restart_strategy.rs
- src/bastion/src/child.rs
- src/bastion/src/children.rs
- src/bastion/src/dispatcher.rs
- src/bastion/src/supervisor.rs
- src/lightproc/examples/state_change.rs
- src/lightproc/tests/stack.rs
> clippy fix, let's see how it goes

- src/bastion-executor/src/placement.rs
- src/bastion-executor/src/run_queue.rs
- src/bastion-executor/src/sleepers.rs
- src/bastion/examples/middleware.rs
- src/bastion/src/bastion.rs
- src/bastion/src/callbacks.rs
- src/bastion/src/child_ref.rs
- src/bastion/src/children.rs
- src/bastion/src/children_ref.rs
- src/bastion/src/config.rs
- src/bastion/src/context.rs
- src/bastion/src/dispatcher.rs
- src/bastion/src/envelope.rs
- src/bastion/src/message.rs
- src/bastion/src/path.rs
- src/bastion/src/supervisor.rs
- src/bastion/src/system.rs
- src/bastion/tests/message_signatures.rs
- src/bastion/tests/prop_children_broadcast.rs
- src/bastion/tests/prop_children_message.rs
- src/bastion/tests/prop_children_redundancy.rs
> Clippy lints

- src/bastion/src/supervisor.rs
I think it's a mistake, I corrected it here.
> Fix supervisor documentation

- src/bastion/examples/round_robin_dispatcher.rs
The goal of this PR is to create an example of a disptacher based on the round robin example.
See #216.
> Add disptacher example

- src/bastion-executor/Cargo.toml
- src/bastion/Cargo.toml
- src/lightproc/Cargo.toml
Issue #226
I did it in the smoothest way, manually.
We have to choose between #228 and it.
> Update dependency versions before release (smoothest way)

- src/bastion/Cargo.toml
- src/bastion/src/bastion.rs
- src/bastion/src/child.rs
- src/bastion/src/children.rs
- src/bastion/src/context.rs
- src/bastion/src/lib.rs
- src/bastion/src/message.rs
- src/bastion/src/supervisor.rs
- src/bastion/src/system.rs
- src/lightproc/Cargo.toml
- src/lightproc/examples/proc_panic.rs
- src/lightproc/examples/proc_run.rs
- src/lightproc/examples/state_change.rs
This drops dependency on futures-preview and futures-0.1 crates
The only caveat is the executor usage in kill
> switch from fqutex to async-mutex

- src/bastion-executor/Cargo.toml
- src/bastion-executor/src/placement.rs
> executor: drop kernel32-sys dependency

- .github/workflows/ci.yml
- src/bastion-executor/src/lib.rs
- src/bastion-executor/src/placement.rs
- src/bastion/examples/round_robin_dispatcher.rs
- src/bastion/src/bastion.rs
- src/bastion/src/children.rs
- src/bastion/src/dispatcher.rs
- src/bastion/src/distributed.rs
- src/bastion/src/executor.rs
- src/bastion/src/macros.rs
- src/bastion/tests/message_signatures.rs
- src/bastion/tests/prop_children_broadcast.rs
- src/bastion/tests/prop_children_message.rs
- src/bastion/tests/prop_children_redundancy.rs
This triggers a feature gate issue we're having, once the tests pass, I'll mark this pr as ready for review
As explained in the cargo check documentation:
> --all: Deprecated alias for --workspace.
This patch adds full checks to our ci builds.
> pass --all-targets --all-features to cargo check and cargo test

- src/bastion/examples/hello_world.rs
Just because it's classic and essential!
> Add hello, world! example

- Cargo.toml
- README.md
- src/bastion-executor/Cargo.toml
- src/bastion/Cargo.toml
- src/bastion/examples/distributed-fwrite.rs
- src/bastion/examples/tcp-servers.rs
- src/bastion/src/io.rs
- src/bastion/src/lib.rs
> IO incorporation

- src/bastion/examples/tcp-servers.rs
40 tcp servers are written when the variables contains 10
> [Examples - tcp-servers] Fixed small typo 

- src/bastion/examples/getting_started.rs
> [Tutorial - Getting started] Add comments on messages type

- src/bastion/src/children_ref.rs
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(d) I understand and agree that this project and the contribution
are public and that a record of the contribution (including all
personal information I submit with it, including my sign-off) is
maintained indefinitely and may be redistributed consistent with
this project or the open source license(s) involved.
> Fix for typo in documention.

- .github/workflows/ci.yml
- src/bastion/Cargo.toml
- src/bastion/examples/distributed-fwrite.rs
- src/bastion/examples/scaling_groups.rs
- src/bastion/examples/tcp-servers.rs
- src/bastion/src/bastion.rs
- src/bastion/src/child_ref.rs
- src/bastion/src/children.rs
- src/bastion/src/lib.rs
- src/bastion/tests/message_signatures.rs
> change ci cd pipeline to let it pass through nuclei

- src/bastion/src/context.rs
Developer's Certificate of Origin 1.1
By making a contribution to this project, I certify that:
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(d) I understand and agree that this project and the contribution
are public and that a record of the contribution (including all
personal information I submit with it, including my sign-off) is
maintained indefinitely and may be redistributed consistent with
this project or the open source license(s) involved.
> Documentation formatting fixes in cross references.

- src/bastion-executor/Cargo.toml
- src/bastion-executor/benches/spawn.rs
- src/bastion-executor/src/load_balancer.rs
> trying to work around allocations in the hot path. to be benchmarked

- src/bastion/examples/broadcast_message.rs
> Fix grammar/typos

- src/bastion-executor/Cargo.toml
- src/bastion-executor/src/thread_manager.rs
- src/bastion/Cargo.toml
- src/bastion/src/context.rs
- src/lightproc/Cargo.toml
Fixes #281 #282 #283 #284 #285 #286
> chore: update dependencies

- src/bastion/src/children.rs
related to #287 . I made changes to the restarted child to use the old state. 
Signed-off-by: பாலாஜி <rbalajis25@gmail.com>
> use old state to restart the child

- src/bastion-executor/Cargo.toml
- src/bastion/Cargo.toml
> bump lever and nuclei

- src/bastion-executor/src/run.rs
- src/bastion/src/context.rs
> Fix clippy warnings

- src/bastion/Cargo.toml
> Bastion executor version alignment

- .github/workflows/miri.yml
- .github/workflows/sanitizers.yml
> bump nightly versions so miri and sanitizers can use the latest available features

- src/bastion-executor/Cargo.toml
- src/bastion/Cargo.toml
Fix #305,  parf of #303 will ease the publish process.
> target minor versions of lightproc instead of patch

- .github/workflows/miri.yml
> update miri flags

- src/bastion/examples/distributed-fwrite.rs
> Fix an issue which-in the service doesn't die when `../data/distwrite`

- src/bastion/examples/broadcast_message.rs
> Change the supervisor creation order in the broadcast message example

- src/bastion/src/children.rs
> Fix a typo in children doc

- src/bastion-executor/Cargo.toml
- src/bastion-executor/src/load_balancer.rs
- src/bastion/Cargo.toml
> bump dependencies

- src/bastion/examples/hello_world.rs
Quick improve of the hello_world example with the new api MessageHandler.
> Improve hello world example with message handler

- src/bastion/examples/distributor.rs
Adding a small dependencies example (for cargo.toml) to get the distributor example running quickly.
> Example: add dependencies to distributor

- src/bastion/src/child.rs
- src/bastion/src/dispatcher.rs
- src/bastion/src/distributor.rs
> unregister from distributors and dispatchers when a child panics
