bastion-rs/bastion

Cargo.toml, benches/bench_one_for_one.rs, src/bastion.rs, src/child.rs, src/context.rs, src/lib.rs, src/runtime_manager.rs, src/runtime_system.rs, src/supervisor.rs, tests/lib.rs, tests/test_shutdown.rs
Implementation of #13.
This implementation was needed for some use cases.
Programmatical shutdown usage is not safe and against the philosophy of this crate.
It shouldn't be used to stop the system.
=> Shutdown implementation

.appveyor.yaml, Cargo.toml, src/bastion.rs
This PR adds support for windows. The PR adds a new appveyor file that will build the project on stable.
This PR is blocked by stable support which should land with #20. Appveyor also needs to be hooked up to the app so that we can get the nice green check before merging. 
This was first discussed in #17
=> Build on windows

benches/bench_one_for_one.rs, examples/root_spv.rs, examples/spawn_from_context.rs, src/bastion.rs, src/context.rs, src/lib.rs, src/runtime_system.rs, src/supervisor.rs, tests/lib.rs
* Refactor supervisors to carry out context to share data between children
On merge resolves #15
=> Spawn from the context

Cargo.toml
Hey :wave:!
https://github.com/rust-lang/cargo/pull/6989 added experimental support for defining custom named profiles in `Cargo.toml` but since we were using a profile named `debug`, which has been renamed to `dev` for some time apparently, cargo decided to throw errors instead of ignoring it and showing warnings.
=> Fixed building on nightly

.github/workflows/ci.yml
`build_and_test_stable` and `build_and_test_nightly` have almost same config.
This change shares config and reduces lines.
=> Clean up actions

.github/workflows/clippy.yml, bastion/src/children.rs, bastion/src/lib.rs, bastion/src/supervisor.rs
Remove deprecated action (`components-nightly`)
Also, fix fmt and some doc to make CI more green
=> Remove deprecated action

bastion/src/bastion.rs, bastion/src/supervisor.rs, bastion/src/system.rs
Hey :wave:!
I moved `ROOT_SPV` (used by `Bastion::children`) out of `lazy_static!` and a `QrwLock`into a `static mut` (I know...). This should be better for when creating new "root-level" children (both performance and contention-wise) but added two `unsafe` blocks to the code.
`ROOT_SPV` is guaranteed to only be written to once (in `System::init`, called inside a `lazy_static!`; and it can't be accessed from outside `system.rs`).
I also fixed a bug making `ROOT_SPV` pointing to a restarted `Supervisor` (thus, with a different `Sender`).
=> Moved ROOT_SPV out of its QrwLock

lightproc/README.md, lightproc/src/lib.rs, lightproc/src/lightproc.rs, lightproc/src/proc_handle.rs, lightproc/src/proc_stack.rs, lightproc/src/recoverable_handle.rs
This improves parts in #59 and #61
=> Lightproc Documentation

bastion/src/bastion.rs, bastion/src/children.rs, bastion/src/context.rs, bastion/src/supervisor.rs, bastion/src/system.rs
=> Disallowing access to the system's supervisor

bastion-executor/src/load_balancer.rs, bastion/src/broadcast.rs
This fetches cores once at the runtime and replaces our continuous fetch of topology.
Possible fix for: #109
=> [executor] Fetch cores at once, rely on runtime

bastion-executor/src/load_balancer.rs, bastion-executor/src/worker.rs, bastion/tests/prop_children_broadcast.rs, bastion/tests/prop_children_message.rs
Job migrators will defer queue migration under the lock contention. Fixes #109 .
=> Ignore migration path under lock contention

bastion/Cargo.toml
Hey :wave:!
I replaced `futures-preview = "=0.3.0-alpha.19"` with `futures = "0.3"` in `bastion`'s `Cargo.toml` :)
=> Replaced "futures-preview" with "futures"

bastion/src/bastion.rs
This Pull Request adds a method to quickly create a children with a given action without having to
use the closure in `Bastion::children`.
```rust
use bastion::prelude::*;
fn main() {
Bastion::init();
let children_ref: ChildrenRef = Bastion::spawn(|ctx: BastionContext| {
async move {
// ...
Ok(())
}
}).expect("Couldn't create the children group.");
Bastion::start();
Bastion::stop();
Bastion::block_until_stopped();
}
```
This change was requested in #116
=> Add Bastion::spawn method

.github/PULL_REQUEST_TEMPLATE.md, README.md
Fix contributing guide link and remove empty support documentation (it already exists on `.github` repo).
Fixes #123
=> Fix link and remove empty doc

bastion/Cargo.toml
Fix failing build. Bump dependency to new bastion-executor version introduced in 71b9649
=> Bump bastion-executor dependency to 0.3.2-alpha.0

bastion/examples/callbacks.rs, bastion/examples/getting_started.rs, bastion/examples/middleware.rs, bastion/examples/parallel_computation.rs, bastion/examples/send_recv.rs, bastion/src/bastion.rs, bastion/src/broadcast.rs, bastion/src/children.rs, bastion/src/context.rs, bastion/src/envelope.rs, bastion/src/lib.rs, bastion/src/message.rs, bastion/src/path.rs, bastion/src/supervisor.rs, bastion/src/system.rs, bastion/tests/message_signatures.rs, bastion/tests/prop_children_message.rs
=> Message Signature to identify message sender and sending messages back

bastion-executor/src/blocking.rs
This PR enables the user to configure thread count with `BASTION_BLOCKING_THREADS` environment variable and enables (if present) thread pinning.
Initial benchmarks showed that this will decrease general variance fluctuations in the high workload.
=> Configurable thread count and thread pinning

bastion/Cargo.toml, bastion/src/lib.rs, bastion/src/supervisor.rs
This pull request gives as opportunity to use an exponential back-off strategy for restarting/recovering failed actors. Also I made it so that it will use the old logic with restoring to the initial state by default.
=> Implemented linear/exponential back off recovery strategy

bastion/examples/restart_strategy.rs, bastion/src/lib.rs, bastion/src/supervisor.rs, bastion/tests/restart_strategy.rs
The following pull request contains the changes for supporting max retries for the failed actors. It covers the #105 and the #146 issues for the bastion project.
By default the restart strategy doesn't have any limits in restating the failed actor, but can be overridden via the special call (which is the `.with_max_retries`).
=> Max retries support for existing restart strategies

bastion-executor/src/pool.rs
The following pull request drops the unused method of the bastion's pool struct, as it was discussed in the #57 issue.
=> Removed Pool::recover_async_thread method

README.md, bastion-executor/Cargo.toml, bastion-executor/src/pool.rs, bastion/Cargo.toml, lightproc/Cargo.toml
=> Roll bastion 0.3.4

bastion/src/lib.rs, bastion/src/message.rs
This pull request moves the `answer` macro to a global scope and re export it in the prelude module
Resolves #118
=> Move answer macro to global scope

bastion/src/callbacks.rs, bastion/src/child.rs, bastion/src/children.rs, bastion/src/context.rs, bastion/src/message.rs, bastion/src/path.rs, bastion/src/supervisor.rs, bastion/src/system.rs
The following feature adds a support for preserving failed actors mailboxes and re-assigned them between restarts. However, those changes require an extensive refactoring of the existing codebase, especially the restart approach that we had before.
=> Preserving actor's mailbox

src/bastion/Cargo.toml, src/bastion/examples/prime_numbers.rs
Now this example is pretty cool.
We have children that serve prime numbers and return them.
We have a supervisor that takes care of children and restarts them if
one fails.
We are using a usize as request type, but a fully fledged Response type
as a result.
info!() logs the successes.
Summary displays how long the program took, and how many failures there
were.
=> Prime numbers example

src/bastion-executor/src/load_balancer.rs, src/bastion-executor/src/sleepers.rs, src/bastion/examples/broadcast_message.rs, src/bastion/src/child_ref.rs, src/bastion/src/children.rs, src/bastion/src/dispatcher.rs
add rustfmt.toml
fix two warnings
for #183
=> add name for children

src/bastion/src/bastion.rs
Use explicitly lazy_static::initialize to trigger initialization instead of calling a method on the lazy value.
Minor thing I noticed while reading through :grin:
=> [Refactor] Explicit initialization for SYSTEM

src/bastion/src/executor.rs, src/bastion/src/lib.rs, src/bastion/src/macros.rs
With these changes we avoid forcing the user to add `bastion_executor` and `lightproc` as direct dependencies if they want to use `blocking!`, `run!` and `spawn!`.
Concern: `RecoverableHandle` is exposed as part of the public API, even though this is just a formalization of what was already happening.
I have matched macro names and function names for simplicity and clarity.
=> Self-contained macros

.github/workflows/ci.yml, src/bastion/Cargo.toml, src/bastion/examples/scaling_groups.rs, src/bastion/src/broadcast.rs, src/bastion/src/child.rs, src/bastion/src/children.rs, src/bastion/src/context.rs, src/bastion/src/dispatcher.rs, src/bastion/src/lib.rs, src/bastion/src/message.rs, src/bastion/src/path.rs, src/bastion/src/resizer.rs, src/bastion/src/supervisor.rs, src/bastion/src/system.rs, src/lightproc/src/proc_handle.rs, src/lightproc/src/recoverable_handle.rs, src/lightproc/src/state.rs
As the part of this PR, I would to introduce the changes that cover needs in autoscaling actor groups in runtime. The initiative was described in the #155 issue.
Before starting with the example, any developers needs to enable the `scaling` feature flag which using for getting an access to desired API, collecting statistical information from actors, etc.
Then, we can import the resizer, and declare the rules around how much actors acceptable (minimal, maximum) for the each actor group. It will be look something like this:
```rust
children
.with_redundancy(3)                                // Start with 3 actors
.with_resizer(
Resizer::default()
.with_lower_bound(0)                       // A minimal acceptable size of group
.with_upper_bound(UpperBound::Limit(10))   // Max 10 actors in …
```
=> Autoscaling actor groups in runtime

src/bastion/src/bastion.rs
Hey, @o0Ignition0o So to get started, I ran the tests only in `Bastion` with:
`cargo test --doc --package bastion -- bastion::Bastion --nocapture`
I was expecting the code blocks in Bastion struct's doc tests to fail as we have an `await!` there.
I am wondering why the tests are passing in `Bastion::*` without this fix? 
Doc tests are run similar to code in a `main` function; right (which doesn't allow `await!`)?
For the fix, I have added the `run!` macro.
Let me know if I missed anything.
=> (docs) use run! instead of await in Bastion docs

src/bastion/examples/round_robin_dispatcher.rs, src/bastion/src/child.rs, src/bastion/src/child_ref.rs, src/bastion/src/children.rs, src/bastion/src/dispatcher.rs
=> dispatch to available children only.

src/bastion/src/supervisor.rs, src/bastion/tests/restart_strategy.rs
Fix issue where fractions of a second are ignored internally. This leads to a broken `RestartStrategy` when given a timeout of eg. `Duration::from_millis(999)`. NOTE: The type casting of `multiplier` can get removed but that would be a breaking change. I leave this for the reviewer to decide.
=> Fix RestartStrategy::timeout < 1s

src/bastion/src/children.rs, src/bastion/src/resizer.rs
```
let mut children = children
.with_redundancy(3) // Start with 3 actors
.with_heartbeat_tick(Duration::from_secs(5)); // Do heartbeat each 5 seconds
#[cfg(feature = "scaling")]
{
children = children.with_resizer(
OptimalSizeExploringResizer::default()
.with_lower_bound(1) // A minimal acceptable size of group
.with_upper_bound(UpperBound::Limit(2)) 
.with_upscale_strategy(UpscaleStrategy::MailboxSizeThreshold(3)) // Scale up when a half of actors have more than 3 messages
.with_upscale_rate(0.1) // Increase the size of group on 10%, if necessary to scale up
.with_downscale_rate(0.2), // Decrease the size of group on 20%, if too many free actors
);
}
```
The above code will panic at https://github.com/bastion-rs/bastion/blob/master/src/bastion/src/resizer.rs#L254 because redundancy is 3 …
=> override the redundancy based on the resizer

src/bastion-executor/src/blocking.rs, src/bastion-executor/src/pool.rs, src/bastion-executor/src/run_queue.rs, src/bastion/src/bastion.rs, src/bastion/src/callbacks.rs, src/bastion/src/child_ref.rs, src/bastion/src/children.rs, src/bastion/src/children_ref.rs, src/bastion/src/config.rs, src/bastion/src/context.rs, src/bastion/src/errors.rs, src/bastion/src/message.rs, src/bastion/src/supervisor.rs
Transitioning to intra-doc-link will allow us to get better feedback about broken
links in the future. It also allows us to remove some annotations that are guessed
by rustdoc.
This PR *should* translate every link to intra-doc-link.
Fix #280.
=> Translate doc link to intra-doc-link, fix broken links

src/bastion/examples/fibonacci_message_handler.rs, src/bastion/examples/message_handler_multiple_types.rs, src/bastion/src/child_ref.rs, src/bastion/src/context.rs, src/bastion/src/message.rs
This PR adds the `MessageHandler` type and its API.
`MsgHandler` allows to match over messages, depending on the message type and on the type of the data they store. It aims to replace the `msg!` macro.
Some public but hidden API is modified, so it should not break code.
Fix #214 .
=> Add MessageHandler

src/bastion/examples/fibonacci_message_handler.rs, src/bastion/examples/message_handler_multiple_types.rs, src/bastion/src/lib.rs
[Previous pull request][1] introduced the MessageHandler datatype, but did
not export it in the prelude.
[1]: https://github.com/bastion-rs/bastion/pull/309
=> Export MessageHandler to the prelude

src/bastion/examples/distributor.rs, src/bastion/src/callbacks.rs, src/bastion/src/child.rs, src/bastion/src/child_ref.rs, src/bastion/src/children.rs, src/bastion/src/context.rs, src/bastion/src/dispatcher.rs, src/bastion/src/distributor.rs, src/bastion/src/errors.rs, src/bastion/src/supervisor.rs, src/bastion/tests/message_signatures.rs
Proposal: Distributor request fn.
as shown [here](https://gist.github.com/o0Ignition0o/2bbb59bf2fdc85c0ee97783b3c2115c6#file-main-rs-L42) making a whole request can sometimes be a bit convoluted. the `Distributor::request()` function aims to be syntactic sugar to wrap this.
```rust
let answer = probes
.ask_one(url.clone())
.expect("couldn't send message to probes");
// Handle a reply
MessageHandler::new(answer.await.expect("couldn't get an answer")).on_tell(
|probe_result: ProbeRunStatus, _| {
info!("probe is done: {:?}", probe_result);
},
);
``` 
will then become
```rust
let probe_run_status: Result<ProbeRunStatus, SendError> = probes
.request(url.clone())
.await
.expect("couldn't receive reply");
info!("probe is done: {:?}", probe_result);
```
It uses a channel() behind the scene, as …
=> proposal: distributor request fn

src/bastion/examples/distributor.rs, src/bastion/src/dispatcher.rs
Because distributors are usable globally by name, it's possible (and
useful) for multiple groups of children to use the same distributor.
However, if one of the groups of children is then stopped as part of the
normal flow of an application, the distributor is removed from the
global dispatcher, and all senders receive an error on trying to send to
that distributor, even if it still has active recipients from other
groups of children.
This commit changes `remove_distributor` in the global dispatcher so
that it checks to see if it still has recipients and only removes the
distributor if there are no remaining recipients.
=> Don't remove a distributor from the global dispatcher if it has clients
